apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-assignment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-assignment
  template:
    metadata:
      labels:
        app: devops-assignment
    spec:
      containers:
      - name: devops-assignment
        image: ghcr.io/saeedtamboli01/devops-assignment:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: ghcr-secret
